version: "3.8"

services:


 nginx:
   build: ./nginx
   image: nginx:latest
   container_name: "nginx_con"
   depends_on:
     - django
   volumes:
     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
     - ./static:/static
     - ./media:/media
     - /etc/letsencrypt/live/www.uxlive.me/fullchain.pem:/etc/letsencrypt/live/www.uxlive.me/fullchain.pem:ro
     - /etc/letsencrypt/live/www.uxlive.me/privkey.pem:/etc/letsencrypt/live/www.uxlive.me/privkey.pem:ro
    
   ports:
     - "80:80"
     - 443:443
   networks:
     - webnet


networks:
    webnet:
        external: true